IDEM-6
dltxio/idem-website pull request #13
Opened 2022-07-18 06:48 UTC by JasminFarhi

![Screen Shot 2022-07-18 at 4 47 11 pm](https://user-images.githubusercontent.com/83386965/179457937-e8b6d105-5ff5-4290-9fca-83e5ab59e9a7.png)

2022-07-18 08:56 UTC, bitcoinbrisbane requested changes
One small thing

2022-07-19 00:00 UTC, bitcoinbrisbane commented on src/components/form.tsx
> +      .post(`http://localhost:3001/user/tester`, JSON.stringify(data), {
Make this a .env value

2022-07-19 00:00 UTC, bitcoinbrisbane requested changes
Make .env

2022-07-19 01:25 UTC, bitcoinbrisbane approved these changes

2022-07-19 01:27 UTC, rellfy approved these changes

2022-07-19 04:57 UTC, merged