APPLE-ID
dltxio/idem-website pull request #17
Opened 2022-07-25 23:50 UTC by JasminFarhi

<img width="1253" alt="Screen Shot 2022-07-26 at 9 49 56 am" src="https://user-images.githubusercontent.com/83386965/180893474-1fe9ecc9-2eb9-485f-9b58-34aaa4556179.png">

2022-07-25 23:54 UTC, brettvniekerk requested changes

2022-07-25 23:54 UTC, brettvniekerk commented on src/components/form.tsx
>                  className="outline-[#ffd000] rounded-3xl text-white bg-black border-white border-2 ml-5 mt-2 px-2 py-2 text-sm w-80"
`p-2` achieves the same thing as `px-2 py-2`

2022-07-25 23:54 UTC, brettvniekerk commented on src/components/form.tsx
>              <div>
Why wrapped in style-less div?

2022-07-26 00:28 UTC, brettvniekerk submitted a review, later dismissed

2022-07-26 05:00 UTC, xiangzhe0812 submitted a review, later dismissed

2022-07-27 23:38 UTC, brettvniekerk submitted a review, later dismissed

2022-07-28 05:45 UTC, xiangzhe0812 approved these changes

2022-07-28 05:59 UTC, bitcoinbrisbane approved these changes

2022-07-28 05:59 UTC, merged